
[package]
name = "lending"
version = "1.0.0"
authors = []

[addresses]
lending_addr = "0x1202bd0151993fd3556212f9f5178fc5239f933beca6389738a5b0872eeea4b1"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dev-dependencies]
